#!/usr/bin/python3

import struct,sys

if len(sys.argv) < 2:
  print("< - LE, > - BE")
  print("B - u8,  b - i8")
  print("H - u16, h - i16")
  print("I - u32, i - i32")
  print("Q - u64, q - i64")
  print("f, d - float32, 64")

fs = "%s"%sys.argv[1]
t = struct.calcsize(fs)

while True:
  r = sys.stdin.readline()
  if not r:
    break
  if "f" in sys.argv[1] or "d" in sys.argv[1]:
    sys.stdout.buffer.write(struct.pack(fs, float(r)))
  else:
    sys.stdout.buffer.write(struct.pack(fs, int(r)))
