#!/bin/sh

gcc -lasan -g -fsanitize=address -fno-omit-frame-pointer -std=gnu11 -Wall -Wextra -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -lm -lpthread -O3 -g -ggdb3 $@ -o `echo $1 | cut -d . -f 1`
